// <auto-generated />
using System;
using AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241009125847_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppData.Models.Danhgia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Hinhanh")
                        .IsRequired()
                        .HasColumnType("Nvarchar(MAX)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Idkh")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDKH");

                    b.Property<string>("Idspchitiet")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSPCHITIET");

                    b.Property<DateTime>("Ngaydanhgia")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYDANHGIA");

                    b.Property<string>("Noidungdanhgia")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("NOIDUNGDANHGIA");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("DANHGIA", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Diachi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Diachicuthe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHICUTHE");

                    b.Property<string>("Idkh")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDKH");

                    b.Property<string>("Phuongxa")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PHUONGXA");

                    b.Property<string>("Quanhuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QUANHUYEN");

                    b.Property<string>("Thanhpho")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("THANHPHO");

                    b.HasKey("Id");

                    b.ToTable("DIACHI", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Giamgia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<int>("Donvi")
                        .HasColumnType("int");

                    b.Property<float>("Giatri")
                        .HasColumnType("real")
                        .HasColumnName("GIATRI");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<DateTime>("Ngaybatdau")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime>("Ngayketthuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("GIAMGIA", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Giamgiatichdiem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Idkh")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDKH");

                    b.Property<string>("Idvoucher")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDVOUCHER");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Id");

                    b.ToTable("GIAMGIA_TICHDIEM", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Giohang", b =>
                {
                    b.Property<string>("Idkh")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDKH");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Idkh");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Giohangchitiet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Idgiohang")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDGIOHANG");

                    b.Property<string>("Idspchitiet")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSPCHITIET");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Id");

                    b.ToTable("GIOHANGCHITIET", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Hinhanh", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Urlhinhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URLHINHANH");

                    b.HasKey("Id");

                    b.ToTable("HINHANH", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Hoadon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Diachiship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHISHIP");

                    b.Property<string>("Donvitrangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DONVITRANGTHAI");

                    b.Property<string>("Idgiamgia")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDGIAMGIA");

                    b.Property<string>("Idkh")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDKH");

                    b.Property<string>("Idnv")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDNV");

                    b.Property<DateOnly>("Ngaygiao")
                        .HasColumnType("date")
                        .HasColumnName("NGAYGIAO");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<DateTime>("Thoigiandathang")
                        .HasColumnType("datetime2")
                        .HasColumnName("THOIGIANDATHANG");

                    b.Property<float>("Tonggiamgia")
                        .HasColumnType("real")
                        .HasColumnName("TONGTIENGIAMGIA");

                    b.Property<float>("Tongtiencantra")
                        .HasColumnType("real")
                        .HasColumnName("TONGTIENCANTRA");

                    b.Property<float>("Tongtiensanpham")
                        .HasColumnType("real")
                        .HasColumnName("TONGTIENSANPHAM");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("Trangthaithanhtoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAITHANHTOAN");

                    b.HasKey("Id");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Hoadonchitiet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<float>("Giamgia")
                        .HasColumnType("real")
                        .HasColumnName("GIAMGIA");

                    b.Property<float>("Giasp")
                        .HasColumnType("real");

                    b.Property<string>("Iddanhgia")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDDANHGIA");

                    b.Property<string>("Idgiamgia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idhoadon")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDHOADON");

                    b.Property<string>("Idspchitiet")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSPCHITIET");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Id");

                    b.ToTable("HOADONCHITIET", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Hoadonnhap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Idnv")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDNV");

                    b.Property<DateTime>("Ngaynhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoigiao")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NGUOIGIAO");

                    b.Property<string>("Sdtnguoigiao")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDTNGUOIGIAO");

                    b.Property<float>("Tongtienhang")
                        .HasColumnType("real")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("HOADONNHAP", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Hoadonnhapchitiet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<float>("Gianhap")
                        .HasColumnType("real")
                        .HasColumnName("GIANHAP");

                    b.Property<string>("Idhoadonnhap")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDHOADONNHAP");

                    b.Property<string>("Idsp")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSP");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Id");

                    b.ToTable("HOADONNHAPCHITIET", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Khachhang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHI");

                    b.Property<int>("Diemsudung")
                        .HasColumnType("int")
                        .HasColumnName("DIEMSUDUNG");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<DateOnly>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN");

                    b.Property<int>("Tichdiem")
                        .HasColumnType("int")
                        .HasColumnName("TICHDIEM");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Lichsuthanhtoan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Idhoadon")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDHOADON");

                    b.Property<DateTime>("Ngaythanhtoan")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYTHANHTOAN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("LICHSUTHANHTOAN", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Nhacungcap", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennhacungcap")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENNHACUNGCAP");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("NHACUNGCAP", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Nhanvien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHI");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HOTEN");

                    b.Property<DateOnly>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Phuongthucthanhtoan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Tenpttt")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENPTT");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("PHUONGTHUCTHANHTOAN", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Sale", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<DateTime>("Ngaybatdau")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime>("Ngayketthuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TEN");

                    b.Property<TimeOnly>("Thoihan")
                        .HasColumnType("time")
                        .HasColumnName("THOIHAN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("SALE", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Salechitiet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<int>("Donvi")
                        .HasColumnType("int")
                        .HasColumnName("DONVI");

                    b.Property<float>("Giamgia")
                        .HasColumnType("real")
                        .HasColumnName("GIAMGIA");

                    b.Property<string>("Idsale")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSALE");

                    b.Property<string>("Idspchitiet")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSPCHITIET");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Id");

                    b.ToTable("SALECHITIET", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Sanpham", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<float>("Giaban")
                        .HasColumnType("real")
                        .HasColumnName("GIABAN");

                    b.Property<float>("Giasale")
                        .HasColumnType("real")
                        .HasColumnName("GIASALE");

                    b.Property<string>("Hinhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tensp")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENSP");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Sanphamchitiet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<float>("Giathoidiemhientai")
                        .HasColumnType("real")
                        .HasColumnName("GIATHOIDIEMHIENTAI");

                    b.Property<string>("Idsp")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSP");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("SANPHAMCHITIET", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Thuoctinh", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Tenthuoctinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENTHUOCTINH");

                    b.HasKey("Id");

                    b.ToTable("THUOCTINH", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Thuoctinhsanphamchitiet", b =>
                {
                    b.Property<string>("Idthuoctinh")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDTHUOCTINH");

                    b.Property<string>("Idspchitiet")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDSPCHITIET");

                    b.Property<string>("Tenthuoctinhchitiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENTHUOCTINHCHITIET");

                    b.HasKey("Idthuoctinh", "Idspchitiet");

                    b.ToTable("THUOCTINH_SANPHAMCHITIET", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Thuonghieu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Tenthuonghieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENTHUONGHIEU");

                    b.Property<string>("Tinhtrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Id");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Trahang", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Chuthich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHUTHICH");

                    b.Property<string>("Idkh")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDKH");

                    b.Property<string>("Idnv")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDNV");

                    b.Property<string>("Lydotrahang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LYDOTRHANG");

                    b.Property<DateTime>("Ngaytrahang")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYTRAHANG");

                    b.Property<string>("Phuongthuchoantien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHUONGTHUCHOANTIEN");

                    b.Property<float>("Sotienhoan")
                        .HasColumnType("real")
                        .HasColumnName("SOTIENHOAN");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENKHACHHANG");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id");

                    b.ToTable("TRAHANG", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Trahangchitiet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID");

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Hinhthucxuly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HINHTHUCXULY");

                    b.Property<string>("Idhoadonchitiet")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("IDHOADONCHITIET");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tinhtrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Id");

                    b.ToTable("TRAHANGCHITIET", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
